### ISSUE TITLE
What languages does it support?

### ISSUE THREAD

**Issue by wjandrea** [wolray/vscode-any-swap#5]
Maybe I'm not understanding the readme correctly, but if it supports operator precedence and uses an AST, isn't that language-specific? So then what languages does the extension support?

---

To be clear, I'm asking about this bit:

> It is based on a general Abstract-Syntax-Tree (AST) analyzer that enables user to swap expressions recursively while maintaining a correct operator precedence.

**Comment by wolray** [comment]
it's not language-specific. the ast is just for simple math expressions, with extra comma and semi-comma. i think it's general enough for most languages. but i cannot guarantee that.
since this extension was build just for swapping parameters, for most use-cases.



---Original---
From: "William ***@***.***&gt;
Date: Thu, Mar 30, 2023 23:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [wolray/vscode-any-swap] What languages does it support? (Issue #5)




 
Maybe I'm not understanding the readme correctly, but if it supports operator precedence and uses an AST, isn't that language-specific? So then what languages does the extension support?
 
 
To be clear, I'm asking about this bit:
  
It is based on a general Abstract-Syntax-Tree (AST) analyzer that enables user to swap expressions recursively while maintaining a correct operator precedence.

**Comment by wjandrea** [comment]
Ah OK, so then its understanding of operator precedence is pretty limited, eh? Like, it knows multiplication (`*`) has higher precedence than addition (`+`), but it doesn't know [comparison operators in Python have the same precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence), so with `4 == 4.0 < 5`, swapping `4` should get `4.0 == 4 < 5`, but instead it gets `4.0 < 5 == 4`.
